Toto je notebook na zistenie, ako čitateľné vstupné dáta sú a prípadné očistenie

In [1]:
import pandas as pd
import matplotlib
import seaborn as sns

In [ ]:
file = "readings.csv"
df = pd.read_csv(file, delimiter="\t", parse_dates=["ts_cycle"], date_format="mixed")

df.query("id_unit == 'U01075'")

,id_unit,ts_cycle,motor_current,dpFilter,temperature_oil,reservoirPressure,oilPressure,rms_vibration,Flowmeter,humidityIntake,failure
8,U01074,2023-10-11,7.32504,16.90241,49.08737,9.16743,4.62081,2.20880,24.82717,NaN,1
5170,U01074,2023-05-24,7.47889,19.28431,48.45512,8.33318,3.65243,5.47652,27.53167,90.40716,0
6183,U01074,2023-08-08,6.75372,9.97078,61.58975,8.95413,4.36086,4.79594,26.99237,32.43661,0
7003,U01074,2023-03-19,7.19362,30.12683,48.30509,9.64958,4.82717,2.08305,32.77834,59.00280,0
9200,U01074,2023-08-06,5.48743,18.13194,64.59981,8.75564,4.05459,3.54655,24.00615,18.98766,0

In [17]:
file = "units.csv"
df = pd.read_csv(file, delimiter=",")

df.sort_values(by="id_unit")

,id_unit,serial_number,year_commission,dutyClass,hours_service,operatorOwner,idDepot
0,1,UJ-6276-85840,2021,N,10733.0,Teixeira Macedo e Filhos,50
1,2,CE-5946-76267,2017,2,26763.3,Benthin Huhn GmbH & Co. KGaA,59
2,3,JH-8720-55338,2023,2,NaN,"Brown, Glover and Williams",68
3,4,OT-1786-88207,2022,2,NaN,Bolnbach,70
4,5,GA-2070-91868,2023,heavy,6964.2,Trapp GmbH,76
...,...,...,...,...,...,...,...
1995,1996,AZ-3337-16607,2019,L,19159.1,Crawford-Mccarthy,44
1996,1997,LY-8013-32401,2024,light,3156.0,Meister,11
1997,1998,BE-8220-94317,2023,N,4647.1,Matias,13
1998,1999,GT-7617-20587,2023,3,5990.0,Spears and Sons,113
1999,2000,OF-0479-22976,2021,L,13865.9,Assunção Neto e Filhos,27