Toto je notebook na zistenie, ako čitateľné vstupné dáta sú a prípadné očistenie

In [2]:
import pandas as pd
import matplotlib
import seaborn as sns

### Analýza štruktúr dát ako súbory
Dataset sa skladá z 3 csv súborov `units.csv`, `readings.csv`, `gateways.csv`

In [6]:
READINGS = "readings.csv"
readings_df = pd.read_csv(READINGS, delimiter="\t", parse_dates=["ts_cycle"], date_format="mixed")
readings_df.head()

,id_unit,ts_cycle,motor_current,dpFilter,temperature_oil,reservoirPressure,oilPressure,rms_vibration,Flowmeter,humidityIntake,failure
0,U01713,2023-04-12,4.53942,17.07120,41.44256,8.31174,3.50095,5.54202,26.60877,43.95098,0
1,U00252,2023-01-20,2.32227,33.57520,67.51767,7.95208,2.84785,2.65594,28.66642,31.12998,0
2,U00822,2023-08-30,7.47554,33.60901,66.09002,9.86046,4.40705,NaN,29.12791,87.72845,0
3,U01266,2023-03-11,7.58163,42.41991,54.71008,7.80329,2.91898,2.47698,36.47254,37.02388,0
4,U01034,2023-06-09,7.34114,17.23080,46.08248,9.06460,4.06547,2.60575,28.06168,65.65696,0

In [14]:
UNITS = "units.csv"
readings_df = pd.read_csv(UNITS, delimiter=",")
readings_df.head()

,id_unit,serial_number,year_commission,dutyClass,hours_service,operatorOwner,idDepot
0,1,UJ-6276-85840,2021,N,10733.0,Teixeira Macedo e Filhos,50
1,2,CE-5946-76267,2017,2,26763.3,Benthin Huhn GmbH & Co. KGaA,59
2,3,JH-8720-55338,2023,2,NaN,"Brown, Glover and Williams",68
3,4,OT-1786-88207,2022,2,NaN,Bolnbach,70
4,5,GA-2070-91868,2023,heavy,6964.2,Trapp GmbH,76

In [12]:
GATEWAYS = "gateways.csv"
gateways_df = pd.read_csv(GATEWAYS, delimiter=";")
gateways_df.head()

,gatewayId,lat,model_hardware,version_firmware,Technician,mac_address,idDepot,id_unit,vendor,Lon,Ipv4,last_seen,dbm_signal,dateInstall
0,GW-00000,40.92527,NODE-7,v1.2.5,Mrs. Stephanie Bartlett,74:f3:ef:c4:30:c9,107,449.0,Preiß GmbH & Co. KG,-9.21042,200.82.55.76,2024-02-11,-76.6,"06/20/2015, 00:00:00"
1,GW-00001,41.03087,NODE-9,v2.7.0,Hans-Otto Weitzel,a2:3f:d6:07:bb:cb,61,1499.0,Ditschlerin Bruder AG,-8.35210,75.246.136.39,03 Sep 2024,-73.4,"12/19/2016, 00:00:00"
2,GW-00002,40.08425,NODE-9,v1.2.5,John Camacho,b4:4b:8e:a1:fc:2c,87,1363.0,Caspar GmbH & Co. KGaA,-7.23610,127.148.71.104,15 Jan 2025,-67.9,17 Sep 2022
3,GW-00003,38.91664,NODE-9,v2.7.0,Elisa Noack-Rogner,fb:c3:5d:4e:44:27,64,447.0,Preiß GmbH & Co. KG,-8.58157,109.188.241.62,"06/09/2024, 00:00:00",-56.7,2021-12-17
4,GW-00004,41.54055,NODE-7,v3.4.1,Shelby Wells,80:d3:e7:6f:07:b8,6,308.0,Tintzmann Hoffmann AG,-8.61346,93.62.149.214,"02/27/2024, 00:00:00",-58.1,27 Jun 2017

In [ ]:
file = "units.csv"
df = pd.read_csv(file, delimiter=",")

df.sort_values(by="id_unit")

,id_unit,serial_number,year_commission,dutyClass,hours_service,operatorOwner,idDepot
0,1,UJ-6276-85840,2021,N,10733.0,Teixeira Macedo e Filhos,50
1,2,CE-5946-76267,2017,2,26763.3,Benthin Huhn GmbH & Co. KGaA,59
2,3,JH-8720-55338,2023,2,NaN,"Brown, Glover and Williams",68
3,4,OT-1786-88207,2022,2,NaN,Bolnbach,70
4,5,GA-2070-91868,2023,heavy,6964.2,Trapp GmbH,76
...,...,...,...,...,...,...,...
1995,1996,AZ-3337-16607,2019,L,19159.1,Crawford-Mccarthy,44
1996,1997,LY-8013-32401,2024,light,3156.0,Meister,11
1997,1998,BE-8220-94317,2023,N,4647.1,Matias,13
1998,1999,GT-7617-20587,2023,3,5990.0,Spears and Sons,113
1999,2000,OF-0479-22976,2021,L,13865.9,Assunção Neto e Filhos,27

In [ ]:
df.query("id_unit == 'U01075'")
readings_df = pd.read_csv(READINGS, delimiter="\t", parse_dates=["ts_cycle"], date_format="mixed")